on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4

      - id: try_fetching_testing_release
        continue-on-error: true
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-TESTING.tar.gz

      - name: There are no TESTING releases, checking regular releases instead
        if: steps.try_fetching_testing_release.outcome == 'failure'
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: rename nightly tar
        run: |
          for file in roc_nightly*tar.gz; do
            mv "$file" roc_nightly.tar.gz
          done

      - name: decompress the tar
        run: tar -xzf roc_nightly.tar.gz

      - run: rm roc_nightly.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      # expect for testing
      - run: sudo apt install -y expect
      - run: expect -v

      # run all tests
      - run: ROC=./roc_nightly/roc ./ci/all_tests.sh
